using System;
using System.Linq;
using System.Text;

using AbstractAlgebraMathSet;

using static AbstractAlgebraStandardGroupS3.Utils;

using static System.Console;

namespace pinter_14_E_3_S3
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.OutputEncoding = Encoding.UTF8;

            S3.ShowOperationTableColored();

            WriteLine("subgroups       : {0}", S3.Subgroups());
            WriteLine("normal subgroups: {0}", S3.NormalSubgroups());

            {
                var H = new[] { ε, β, σ }.ToMathSet(); // <β>   subgroup   normal   generated by β

                // xa = a^k x

                foreach (var x in S3.Set)
                {
                    var xa = S3.Op(x, β);

                    var k_ = Enumerable.Range(1, 10).First(k => S3.Op(S3.OpN(β, k), x) == xa);

                    Write("{0}{1} = {2}    ", S3.Lookup(x), S3.Lookup(β), S3.Lookup(S3.Op(x, β)));

                    WriteLine("β^{0} {1} = {2}{1} = {3}", 
                        k_, 
                        S3.Lookup(x),
                        S3.Lookup(S3.OpN(β, k_)),
                        S3.Lookup(S3.Op(S3.OpN(β, k_), x)));
                }

            }

        }
    }
}
