using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using AbstractAlgebraMathSet;
using AbstractAlgebraGroup;
using AbstractAlgebraGapPerm;

using static System.Console;

namespace pinter_14_E_3_S3
{
    class Program
    {
        static void Main(string[] args)
        {
            var ε = new GapPerm(0);         // new FunctionIntInt((1, 1), (2, 2), (3, 3));
            var α = new GapPerm("(23)");    // new FunctionIntInt((1, 1), (2, 3), (3, 2));
            var β = new GapPerm("(132)");   // new FunctionIntInt((1, 3), (2, 1), (3, 2));
            var γ = new GapPerm("(12)");    // new FunctionIntInt((1, 2), (2, 1), (3, 3));
            var σ = new GapPerm("(123)");   // new FunctionIntInt((1, 2), (2, 3), (3, 1));
            var κ = new GapPerm("(13)");    // new FunctionIntInt((1, 3), (2, 2), (3, 1));

            string lookup(GapPerm f)
            {
                var items = new[] { (ε, "ε"), (α, "α"), (β, "β"), (γ, "y"), (σ, "σ"), (κ, "k") };

                return items.First(elt => f == elt.Item1).Item2;
            }

            var S_3 = new Group<GapPerm>
            {
                Identity = ε,
                Set = new MathSet<GapPerm>(new[] { ε, α, β, γ, σ, κ }),
                Op = (a, b) => a.Compose(b),
                Lookup = lookup
            };

            S_3.ShowOperationTableColored();

            WriteLine("subgroups       : {0}", S_3.Subgroups());
            WriteLine("normal subgroups: {0}", S_3.NormalSubgroups());

            {
                var H = new[] { ε, β, σ }.ToMathSet(); // <β>   subgroup   normal   generated by β

                // xa = a^k x

                foreach (var x in S_3.Set)
                {
                    var xa = S_3.Op(x, β);

                    var k_ = Enumerable.Range(1, 10).First(k => S_3.Op(S_3.OpN(β, k), x) == xa);

                    Write("{0}{1} = {2}    ", S_3.Lookup(x), S_3.Lookup(β), S_3.Lookup(S_3.Op(x, β)));

                    WriteLine("β^{0} {1} = {2}{1} = {3}", 
                        k_, 
                        S_3.Lookup(x),
                        S_3.Lookup(S_3.OpN(β, k_)),
                        S_3.Lookup(S_3.Op(S_3.OpN(β, k_), x)));
                }

            }

        }
    }
}
